### ISSUE TITLE
the pill is too fat

### ISSUE THREAD

**Issue by yuholqjn** [OokTech/TW5-GenTags#1]
I drag the plugin into my wiki，but when I make new field，the pill is too fat。
how to solve this problem？
thanks！

![QQ图片20230819214118](https://github.com/OokTech/TW5-GenTags/assets/108602378/962b73a9-6f58-4cd0-bfd7-9ff2fa3a4340)

**Comment by calminu** [comment]
I suspect this is a conflict with how newer TWs are rendered; I noticed it when updating from TW 5.2.1 to 5.2.3, and rolling back to 5.2.1 resolved it. (So far, I haven't missed the newer versions' tweaks more than I would miss GenTags.)

**Comment by inmysocks** [comment]
I have finally gotten around to fixing this, but the repo has moved to gitlab. The repo is here https://gitlab.com/ooktech-tw/plugins/gentags and the demo page is here https://ooktech-tw.gitlab.io/plugins/gentags/
